### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by anroysko** [doc97/GOAPer#1]
Päivä ja kellonaika: 20.4, ~20
	
En ole kyllä aivan varma mitä ongelmaa tässä yritetään ratkaista, joten saatan olla väärässä, mutta,

Jos ongelma on rajoittunut booleaneihin dagissa, optimaalisen ratkaisun saa helposti lineaarisessa ajassa pitämällä yllä lopulliseen tavoitteeseen tarvittavia prerequisite-actioneja jotka voi tehdä, ja suorittamalla niitä yksi kerrallaan, samalla tarkistaen onko jokin uusi prerequisite-action nyt mahdollinen.

Yleisemmässä tapauksessa, jos jokin actionien property estää aikaisemman, kuten esim jos action vaatii muuttujan olevan positiivinen, ja jotkin actionit vähentävät tätä muuttujaa, käyttämällä dp:tä kaikkien statejen yli, niin että tilassa säilytetään minimipenalty, voi saavuttaa tyyppiä 2^n aikavaatimuksen n^n sijasta. Käytännössä dp on kyllä varmaan hidas, koska siihen on vaikea saada mitään heuristiikkoja.

HeapAlgorithm:n rivillä 82,
```plans.addAll(plansToAdd);```
Tämä rivi tekee, jos k on lisättävien määrä, k log(k) työtä. Tekemällä vaan
```
PriorityQueue<SubPlan> tmp = plans;
plans = plansToAdd;
plansToAdd = tmp;
```
Saavuttaa saman asian vakiomäärällä työtä, koska tässä kohdassa plans on aina tyhjä. Ei kyllä vaikuta koko algon aikavaativuuteen.

Testit toimivat hyvin.

Pikkujuttuja:
- help-komento ei listaa use-komentoa.
- wikissä sivulla "What is GOAP?" linkit wikin muille sivuille ovat hajalla

**Comment by doc97** [comment]
Kiitos katselmoinnista!

En oikein ymmärtänyt mitä tarkoitit "dp":llä, voisitko selittää? Pahoittelen jos dokumentaatio oli hämmentävä, tein suuren osan siitä tällä viikolla eli sieltä löytyy varmaan kohtia joita voisi parantaa. 

Olet oikeassa että addAll lisää niitä yksi kerralla mikä on "hidasta". Nice one.

help komento on jäänyt vähän jälkeen, mutta dokumentaatiossa pitäisi lukea kaikki mahdolliset komennot. Puute oli tiedossa, mutta hyvin huomattu :smile: 

Korjasin linkit "What is GOAP?"-sivulla.

**Comment by doc97** [comment]
Halusin vielä selventää pari asiaa:

1. GOAPer tukee tällä hetkellä `integer` tyyppisiä muuttujia, joilla voi mallintaa `boolean` (0 tai 1).
2. Demoa varten `formulateAllPlans` laskee siis tällä hetkellä kaikki mahdolliset tavat päästä maaliin. Eli se ei pysähdy kuin paras mahdollinen "reitti" on löytynyt, mikä on vähän tyhmää.
